# Role entrypoint
- name: Install HAProxy
  ansible.builtin.import_tasks: install.yml
  tags:
    - haproxy
    - haproxy_install

- name: Configure HAProxy
  ansible.builtin.import_tasks: configure.yml
  tags:
    - haproxy
    - haproxy_configure
