# Reverse proxy
- name: Installs haproxy load balancer
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Pushes template configuration (not a copy) (to /etc/haproxy/haproxy.cfg)
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Sets default starting flag to 1
  ansible.builtin.lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED"
    line: "ENABLED=1"
  notify: restart haproxy
