namespace: "ansible"
name: "collection_ansible"
version: "1.0"
readme: "README.md"
authors:
    - "BESILY Michaël"
    - "MOUËZANT Antoine"
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://www.github.com/my_org/my_collection"