# Playbook pour les serveurs web
- name: Web
  hosts: web
  become: true
  roles:
    - apache

# Playbook pour le reverse proxy
- name: Haproxy
  hosts: haproxy
  become: true
  roles:
    - reverseproxy


# Playbook pour les utilisateurs
- name: Users
  hosts: users
  become: true
  roles:
    - users
