# Playbook pour les serveurs web
- name: Web
  hosts: web
  become: true
  roles:
    - apache

# Playbook pour le reverse proxy
- name: Haproxy
  hosts: haproxy
  become: true
  collections:
    - sigma.haproxy
  roles:
    - haproxy


# Playbook pour les utilisateurs
- name: Users
  hosts: users
  become: true
  roles:
    - users
