# Apache
- name: Installs necessary packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apache2
      - git
      - htop

- name: Deploy our awesome application
  ansible.builtin.git:
    repo: "https://github.com/TiJof/ansible-tuto-demosite.git"
    dest: "/var/www/awesome-app"
  tags: deploy

- name: Push virtual host configuration
  ansible.builtin.copy:
    src: awesome-app.conf
    dest: /etc/apache2/sites-available/awesome-app.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: backup_file
  notify:
    - restart apache


- name: Create awesome-app web root
  ansible.builtin.file:
    path: /var/www/awesome-app/
    state: directory
    owner: root
    mode: '0755'

- name: Remove the default virtualhost
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache

- name: Remove the default ssl virtualhost
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    state: absent
  notify:
    - restart apache


- name: Activates our virtualhost
  ansible.builtin.file:
    src: /etc/apache2/sites-available/awesome-app.conf
    dest: /etc/apache2/sites-enabled/awesome-app.conf
    state: link
  notify:
    - restart apache

- name: Check that our config is valid
  command: apache2ctl configtest
  register: check_result
  ignore_errors: True

- name: Rolling back - Restoring our virtualhost
  when: check_result is failed
  ansible.builtin.copy:
    src: "{{backup_file.backup_file}}"
    dest: /etc/apache2/sites-available/awesome-app.conf
    remote_src: yes
    owner: root
    group: root

- name: Rolling back - Ending playbook
  ansible.builtin.fail:
    msg: "Configuration file is not valid. Please check that before re-running the playbook."
  when: check_result is failed
