
# Playbook pour les serveurs web
- hosts: web
  become: true
  roles:
    - apache

# Playbook pour le reverse proxy
- hosts: haproxy
  become: true
  roles:
    - reverseproxy


# Playbook pour les utilisateurs
- hosts: users
  become: true
  roles:
    - users
